### ISSUE TITLE
Update PROMPT_COMMAND without overwrite old value

### ISSUE THREAD

**Issue by zhongweiy** [randymorris/tramp-term.el#7]
Hi, `tramp-term--initialize` will set `PROMPT_COMMAND` environment variable to `set-eterm-dir`  currently, which will overwrite its old value. What about this way:
`
PROMPT_COMMAND=\"${PROMPT_COMMAND:+$PROMPT_COMMAND ;} set-eterm-dir\"
`

**Comment by randymorris** [comment]
Sorry for taking so long to comment on this, somehow I missed the notification.  I don't really see any harm in this.  Can you open a pull request and I'll merge it in?  Thanks!

**Comment by zhongweiy** [comment]
@randymorris done, please take a look.
